/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-05-19 05:41:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MOVIETRAP/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/D:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MOVIETRAP/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1620715428411L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1620715428414L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<link href=\"assets/css/header.css\" type=\"text/css\" rel=\"stylesheet\" >  \r\n");
      out.write("<title>Header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"logo\" onclick=\"location='main.jsp'\">\r\n");
      out.write("\t\t\t\t<img src=\"assets/images/logo.png\" /> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"search\">\r\n");
      out.write("\t\t\t<input type=\"search\" placeholder=\"search\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"genre\">\r\n");
      out.write("\t\t\t<select>\r\n");
      out.write("\t\t\t\t<option value=\"genre1\">Horror</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre2\">Romantic Comedy</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre3\">SF/Fantasy</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre4\">Thriller</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre5\">Drama</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre6\">Documentary</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre7\">Mystery</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre8\">Comedy</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre9\">Action</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre10\">Animation</option>\r\n");
      out.write("\t\t\t\t<option value=\"genre11\">Kids</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"user_icon\" onclick=\"location='MOVIETRAPServlet?command=membership'\">\r\n");
      out.write("\t\t\t<img src=\"assets/images/user.png\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"watch_later\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"assets/images/heart.png\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"set\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"assets/images/set.png\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html >\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<link href=\"assets/css/main.css\" type=\"text/css\" rel=\"stylesheet\"> \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/li\r\n");
      out.write("bs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<title>MOVIETRAP</title> \r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: black;\">\r\n");
      out.write("\t<div id=\"main_movie\">\r\n");
      out.write("\t\t<div id=\"main_movie_trailer\" >\r\n");
      out.write("\t\t<iframe width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/kRpkRkO9KUI\">\r\n");
      out.write("\t\t</iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"main_movie_info\">\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"main_movie_title\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" value=\"Main Movie Title\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"main_movie_description\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" value=\"description\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"main_play_button\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"play\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"main_watch_later\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"play\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<div id=\"thumbnail_slideshow_wrapper\">  \r\n");
      out.write("\t<div class=\"thumbnail_slideshow_row\">  \r\n");
      out.write("\t\t<div id=\"thumbnail_wrapper\" > \r\n");
      out.write("\t\t\t<img id=\"slideLeft\" class=\"arrow\" src=\"assets/images/heart.png\">\r\n");
      out.write("\t\t\t<div id=\"trend_movie\" style=\"height: 300px; overflow-x:hidden;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail0\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail1\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail2\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail3\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail4\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail5\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail6\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail7\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail8\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail9\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail10\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail11\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail12\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail13\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail14\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail15\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail16\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail17\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail18\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail19\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail20\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail21\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail22\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail23\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img class=\"thumbnail24\" src=\"assets/images/heart.png\" style=\"display: none;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<img id=\"slideRight\" class=\"arrow\" src=\"assets/images/heart.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- QNA pop up -->\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"chat-box\">\r\n");
      out.write("<div class=\"chat-closed\"> Chat Now </div>\r\n");
      out.write("<div class=\"chat-header hide\"><div class=\"box\"></div>Online Support</div>\r\n");
      out.write("<div class=\"chat-content-container hide\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"chat-content\">\r\n");
      out.write("\r\n");
      out.write("*<br>\r\n");
      out.write("Your chat content...\r\n");
      out.write("*<br>\r\n");
      out.write("\r\n");
      out.write("*<br>\r\n");
      out.write("Your chat content…\r\n");
      out.write("</div>\r\n");
      out.write("<!-- \t<div id =\"chat-input\"> -->\r\n");
      out.write("\t\t<textarea  id =\"chat-input\" name=\"item3\" cols=\"30\" rows=\"5\"></textarea> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("<!-- \t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<div id=\"chat-submit\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"send\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//pic slide \r\n");
      out.write("\tlet buttonRight = document.getElementById('slideRight');\r\n");
      out.write("\tlet buttonLeft = document.getElementById('slideLeft');\r\n");
      out.write("\r\n");
      out.write("\tbuttonLeft.addEventListener('click', function(){\r\n");
      out.write("\t\tdocument.getElementById('trend_movie').scrollLeft -= 500\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\tbuttonRight.addEventListener('click', function(){\r\n");
      out.write("\t\tdocument.getElementById('trend_movie').scrollLeft += 500\r\n");
      out.write("})\r\n");
      out.write("//qna\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\".chat-closed\").on(\"click\",function(e){\r\n");
      out.write("        $(\".chat-header,.chat-content-container\").removeClass(\"hide\");\r\n");
      out.write("        $(this).addClass(\"hide\");\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(\".chat-header\").on(\"click\",function(e){\r\n");
      out.write("        $(\".chat-header,.chat-content-container\").addClass(\"hide\");\r\n");
      out.write("        $(\".chat-closed\").removeClass(\"hide\");\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("//movie info AJAX\t\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\t$.ajax ({\r\n");
      out.write("\t\t\turl : \"MOVIETRAPServlet?command=main\",\r\n");
      out.write("\t\t\tasync : false,\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\tconst json =  JSON.parse(result)\r\n");
      out.write("\t\t\t\tvar trend = json[\"trendData\"]\r\n");
      out.write("\t\t\t\tvar pop = json[\"popData\"]\r\n");
      out.write("\t\t\t\tvar video = json[\"videoData\"]\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (var i = 0; i<= Object.keys(trend).length; i++){\r\n");
      out.write("\t\t\t\t\t$('.thumbnail' + i).attr('src', 'http://image.tmdb.org/t/p//w200' + trend[Object.keys(trend)[i]][\"poster_path\"]);\r\n");
      out.write("\t\t\t\t\t$('.thumbnail' + i).css('display', 'block');\r\n");
      out.write("\t\t\t\t\tconsole.log(\"title : \" + trend[Object.keys(trend)[i]][\"title\"])\r\n");
      out.write("\t\t\t\t\tconsole.log(\"overview : \" + trend[Object.keys(trend)[i]][\"overview\"])\r\n");
      out.write("\t\t\t\t\tconsole.log(\"vote_average : \" + trend[Object.keys(trend)[i]][\"vote_average\"])\r\n");
      out.write("\t\t\t\t\tconsole.log(\"poster_path : \" + trend[Object.keys(trend)[i]][\"poster_path\"])\r\n");
      out.write("\t\t\t\t\tconsole.log('http://image.tmdb.org/t/p/original' + trend[Object.keys(trend)[i]][\"poster_path\"])\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax : fail\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
